<a href="https://colab.research.google.com/github/changsin/ML/blob/main/PCA/Week3.projections.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PCA: Week 3 - Projections



## Projection onto 1D subspaces
1. Dot product is inner product of matrices.
$$ \pi_u (x) = \frac{x^Tb}{||b||^2}b $$


## Assignment

Recall that for projection of a vector $\boldsymbol x$ onto a 1-dimensional subspace $U$ with basis vector $\boldsymbol b$ we have

$${\pi_U}(\boldsymbol x) = \frac{\boldsymbol b\boldsymbol b^T}{{\lVert\boldsymbol  b \rVert}^2}\boldsymbol x $$

And for the general projection onto an M-dimensional subspace $U$ with basis vectors $\boldsymbol b_1,\dotsc, \boldsymbol b_M$ we have

$${\pi_U}(\boldsymbol x) = \boldsymbol B(\boldsymbol B^T\boldsymbol B)^{-1}\boldsymbol B^T\boldsymbol x $$

where 

$$\boldsymbol B = [\boldsymbol b_1,...,\boldsymbol b_M]$$


Your task is to implement orthogonal projections. We can split this into two steps
1. Find the projection matrix $\boldsymbol P$ that projects any $\boldsymbol x$ onto $U$.
2. The projected vector $\pi_U(\boldsymbol x)$ of $\boldsymbol x$ can then be written as $\pi_U(\boldsymbol x) = \boldsymbol P\boldsymbol x$.

To perform step 1, you need to complete the function `projection_matrix_1d` and `projection_matrix_general`. To perform step 2, complete `project_1d` and `project_general`.

### Quiz

#### Question 1
Compute the projection matrix that allows us to project any vector $ \mathbf{x}\in\mathbb{R}^3 $ onto the subspace spanned by the basis vector $ \mathbf{b} = \begin{bmatrix} 1 \\ 2 \\ 2 \end{bmatrix} $​

In [25]:
import numpy as np
def length(x):
  return np.dot(x.T, x)

def projection_matrix(b):
  return np.matmul(b, b.T)/(length(b)*length(b))

b = np.array([[1], [2], [2]])
projection_matrix(b)

array([[0.01234568, 0.02469136, 0.02469136],
       [0.02469136, 0.04938272, 0.04938272],
       [0.02469136, 0.04938272, 0.04938272]])

In [3]:
b = np.array([1, 2, 2])

In [11]:
np.outer(b, b.T)

array([[1, 2, 2],
       [2, 4, 4],
       [2, 4, 4]])

In [10]:
b = np.array([1, 2, 2])
np.outer(b, b)

array([[1, 2, 2],
       [2, 4, 4],
       [2, 4, 4]])

In [12]:
np.linalg.norm(b)

3.0

In [27]:
b

array([[1],
       [2],
       [2]])

In [28]:
np.linalg.inv(b)

LinAlgError: ignored

In [21]:
np.linalg.inv([[3, 3],[3, 5]])

array([[ 0.83333333, -0.5       ],
       [-0.5       ,  0.5       ]])

### Question 2
Given the projection matrix
$ \displaystyle\frac{1}{25}
 \begin{bmatrix} 
  9 & 0 & 12 \\
  0 & 0 & 0 \\
  12 & 0 & 16
  \end{bmatrix}
$

project $
 \begin{bmatrix} 
  1 \\ 1 \\ 1
  \end{bmatrix}
$​ onto the corresponding subspace, which is spanned by
$ \mathbf{b} = \begin{bmatrix} 3 \\ 0 \\ 4 \end{bmatrix} $


#### Question 3
Now, we compute the reconstruction error, i.e., the distance between the original data point and its projection onto a lower-dimensional subspace.

Assume our original data point is 
$
 \begin{bmatrix} 
  1 \\ 1 \\ 1
  \end{bmatrix}
$​ and its projection
$\frac{1}{9}
 \begin{bmatrix} 
  5 \\ 10 \\ 10
  \end{bmatrix}
$​. What is the reconstruction error?

In [15]:
def distance(x, y):
  delta = x - y
  return np.sqrt(np.matmul(delta.T, delta))

x = np.array([1, 1, 1])
xp = (1/9) * np.array([5, 10, 10])

distance(x, xp)

0.4714045207910317

## Practice Quiz


#### Question 1

In [15]:
x = np.array([[6], [0], [0]])
b1 = np.array([[1], [1], [1]])
b2 = np.array([[0], [1], [2]])
B = np.array([[1, 0], [1, 1], [1, 2]])
B

array([[1, 0],
       [1, 1],
       [1, 2]])

In [16]:
proj_matrix = np.matmul(np.matmul(B, np.matmul(B.T, B)), B.T)

In [17]:
np.matmul(proj_matrix, x)

array([[18],
       [36],
       [54]])

In [18]:
proj_matrix @ x

array([[18],
       [36],
       [54]])

#### Question 2

In [33]:
def project(x, B):
  # proj_matrix = np.matmul(np.matmul(B, np.matmul(B.T, B)), B.T)

  # proj_matrix = B @ np.linalg.inv(B.T @ B) @ B.T
  proj_matrix = B @ (np.linalg.inv(B.T @ B)) @ B.T
  return np.matmul(proj_matrix, x)

x = np.array([[3], [2], [2]])
B = np.array([[1, 0], [0, 1], [0, 1]])
project(x, B)

array([[3.],
       [2.],
       [2.]])

#### Question 3
project x to B

In [34]:
x = np.array([[12], [0], [0]])
B = np.array([[1, 0], [1, 1], [1, 2]])
project(x, B)

array([[10.],
       [ 4.],
       [-2.]])

project the projected result onto

In [35]:
b3 = np.array([[-10*np.sqrt(6)], [-4*np.sqrt(6)], [2*np.sqrt(6)]])